name: Docker Image CI/CD

on:
  push:
    branches: [ "prod" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare tag
        id: prep
        run: echo ::set-output name=tag::$(echo $(date +%Y%m%d%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7))
      - name: Build the Docker image
        run: docker build --tag slimon110/sushi-backend:${{ steps.prep.outputs.tag }} --file backend/Dockerfile .

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push to Docker Hub
        run: docker push slimon110/sushi-backend:${{ steps.prep.outputs.tag }}
      
      - name: Trigger Azure Webhook
        run: >
          # curl -X POST ${{ secrets.AZURE_WEBHOOK_URL }}
          curl -X POST https://$sushi-backend2:SJ5zKnaXetJN7vncgyBrMjtRFEs1WJdq5mouyJtt9rb5JSZZ3QvnaunpnxxX@sushi-backend2.scm.azurewebsites.net/api/registry/webhook
